version: '3.7'
services:
  logger:
    build:
      context: ./
      dockerfile: ./logger/Dockerfile
    container_name: slack-patron-logger
    volumes:
      - ./config.yml:/usr/local/slack-patron/config.yml
    depends_on:
      - mongo
    restart: always
    networks:
      - slack-patron-network

  viewer:
    build:
      context: ./
      dockerfile: ./viewer/Dockerfile
    container_name: slack-patron-viewer
    volumes:
      - ./config.yml:/usr/local/slack-patron/config.yml
    ports:
      - 9292:9292
    depends_on:
     - mongo
    restart: always
    networks:
      - proxy-network
      - slack-patron-network
    environment:
      - VIRTUAL_HOST
      - VIRTUAL_PORT=9292
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
      - BASIC_AUTH_USERNAME
      - BASIC_AUTH_PASSWORD

  mongo:
    image: mongo
    command: --logpath=/var/log/mongodb/mongo.log --profile=1 --slowms=100
    volumes:
      - datadir:/data/db
      - mongo-log:/var/log/mongodb
    ports:
        - "27018:27017"
    restart: always
    networks:
      - slack-patron-network

volumes:
  datadir:
  mongo-log:

networks:
  proxy-network:
    external:
      name: proxy_network
  slack-patron-network:
    name: slack_patron_network

